version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          APP_SETTINGS: testing
    steps:
      - checkout
      - run:
          name: Setup environnement
          command: |
            pip install --no-cache-dir --user -r requirements.txt
      - run:
          name: Run Tests
          command: | 
            python3 -m unittest
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_LOGIN/python-devpool-back .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/python-devpool-back
