version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Setup environnement
          command: |
            pip install --no-cache-dir --user -r requirements.txt
      - run:
          name: Run Tests
          command: | 
            python3 -m unittest
